config/routes.rb
Recortables3d::Application.routes.draw do

  resources :imagenes
  resources :modelos
  resources :recortables

  resource :bienvenida, :only => :show, :controller => :bienvenida

   root :to => "bienvenida#show"

end

app/controllers/imagenes_controller.rb
class ImagenesController < ApplicationController

  def index
    @imagenes = Imagen.all
  end
  
  def show
    @imagen = Imagen.find(params[:id])
  end
  
  def new
    @imagen = Imagen.new
  end
  
  def create
    @imagen = Imagen.new(params[:imagen])
    if @imagen.save
      flash[:notice] = "Successfully created imagen."
      redirect_to @imagen
    else
      render :action => 'new'
    end
  end
  
  def edit
    @imagen = Imagen.find(params[:id])
  end
  
  def update
    @imagen = Imagen.find(params[:id])
    if @imagen.update_attributes(params[:imagen])
      flash[:notice] = "Successfully updated imagen."
      redirect_to @imagen
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @imagen = Imagen.find(params[:id])
    @imagen.destroy
    flash[:notice] = "Successfully destroyed imagen."
    redirect_to imagenes_url
  end
end

app/helpers/imagenes_helper.rb
module ImagenesHelper
end

app/views/imagenes/_form.html.erb
<% form_for @imagen do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/imagenes/edit.html.erb
<% title "Edit Imagen" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @imagen %> |
  <%= link_to "View All", imagenes_path %>
</p>

app/views/imagenes/index.html.erb
<% title "Imagenes" %>

<table>
  <tr>
    <th>Nombre</th>
  </tr>
  <% for imagen in @imagenes %>
    <tr>
      <td><%=h imagen.nombre %></td>
      <td><%= link_to "Show", imagen %></td>
      <td><%= link_to "Edit", edit_imagen_path(imagen) %></td>
      <td><%= link_to "Destroy", imagen, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Imagen", new_imagen_path %></p>

app/views/imagenes/new.html.erb
<% title "New Imagen" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", imagenes_path %></p>

app/views/imagenes/show.html.erb
<% title "Imagen" %>

<p>
  <strong>Nombre:</strong>
  <%=h @imagen.nombre %>
</p>

<p>
  <%= link_to "Edit", edit_imagen_path(@imagen) %> |
  <%= link_to "Destroy", @imagen, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", imagenes_path %>
</p>