config/routes.rb
Recortables3d::Application.routes.draw do

  resources :imagenes
  resources :modelos
  resources :recortables

  resource :bienvenida, :only => :show, :controller => :bienvenida

   root :to => "bienvenida#show"

end

app/controllers/recortables_controller.rb
class RecortablesController < ApplicationController

  def index
    @recortables = Recortable.all
  end
  
  def show
    @recortable = Recortable.find(params[:id])
  end
  
  def new
    @recortable = Recortable.new(:color_fondo => '#118833', :color_aristas => '#442211')
    carga_combos
  end
  
  def create
    @recortable = Recortable.new(params[:recortable])
    if @recortable.save
      #flash[:notice] = t :recortable_creado

      if params[:commit] == t(:previsualizar)
        redirect_to edit_recortable_path(@recortable)
      else
        redirect_to @recortable
      end

    else
      carga_combos
      render :action => 'new'
    end
  end
  
  def edit
    @recortable = Recortable.find(params[:id])
    carga_combos
  end
  
  def update    
    @recortable = Recortable.find(params[:id])
    if @recortable.update_attributes(params[:recortable])
      #flash[:notice] = t :recortable_actualizado
      if params[:commit] == t(:previsualizar)
        redirect_to edit_recortable_path(@recortable)
      else
        redirect_to root_path
      end
    else
      carga_combos
      render :action => 'edit'
    end
  end
  
  def destroy
    @recortable = Recortable.find(params[:id])
    @recortable.destroy
    #flash[:notice] = t :recortable_eliminado
    redirect_to root_path
  end

  def carga_combos
    @modelos = Modelo.lista_select    
    @complejidad = Recortable.lista_select_complejidad
    @grosor_aristas = Recortable.lista_select_grosor_aristas
  end
  private :carga_combos

end

app/helpers/recortables_helper.rb
module RecortablesHelper

  def lista_imagenes_recortable
    array_imagenes = []

    if @recortable.nombre.blank?
      array_imagenes << "esfera320.jpg"
      array_imagenes << "esfera320.jpg"
      array_imagenes << "esfera320.jpg"
      array_imagenes << "esfera320.jpg"
    elsif @recortable.nombre && @recortable.imagenes.empty?
      #Personalizada
      case @recortable.nombre
        when "Bolo16"
        array_imagenes << "bolo16.jpg"
        when "Bolo35"
        array_imagenes << "bolo35.jpg"
        when "Bolo70"
         array_imagenes << "bolo70.jpg"
        when "Bolo154"
          array_imagenes << "bolo154.jpg"
        when "Bolo340"
          array_imagenes << "bolo340.jpg"
        when "Cono_r_h"
          array_imagenes << "cono_r_h.jpg"
        when "Cono_r_2h"
          array_imagenes << "cono_r_2h.jpg"
        when "Cono_2r_h"
          array_imagenes << "cono_2r_h.jpg"
        when "Cono_4r_h"
          array_imagenes << "cono_4r_h.jpg"
        when "Esfera20"
          array_imagenes << "esfera20.jpg"
        when "Esfera80"
          array_imagenes << "esfera80.jpg"
        when "Esfera320"
          array_imagenes << "esfera320.jpg"
          break;
        else
          array_imagenes << "esfera320.jpg"
      end
    else
      # Imagenes del recortable.
      array_imagenes = @recortable.imagenes.map{|k| k.imagen.url}
    end
  end
end

app/views/recortables/_form.html.haml
#formulario
  %div{:class => "coda-slider-wrapper"}
    %div{:class=>"coda-slider preload", :id=>"coda-slider-formulario"}
      - form_for @recortable, :html => {:multipart => true, :class => "bp"} do |f|
        %div.panel
          %div.panel-wrapper
            %table
              %tr
                %td
                  = f.radio_button :nombre, "Bolo16"
                  = f.label "Bolo 16"
                  %br
                  = f.radio_button :nombre, "Bolo35"
                  = f.label "Bolo 35"
                  %br
                  = f.radio_button :nombre, "Bolo70"
                  = f.label "Bolo 70"
                  %br
                  = f.radio_button :nombre, "Bolo154"
                  = f.label "Bolo 154"
                  %br
                  = f.radio_button :nombre, "Bolo340"
                  = f.label "Bolo 340"
                %td
                  = f.radio_button :nombre, "Cono_r_h"
                  = f.label "Cono r=h"
                  %br
                  = f.radio_button :nombre, "Cono_r_2h"
                  = f.label "Cono r=2h"
                  %br
                  = f.radio_button :nombre, "Cono_2r_h"
                  = f.label "Cono 2r=h"
                  %br
                  = f.radio_button :nombre, "Cono_4r_h"
                  = f.label "Cono 4r=h"
                %td
                  = f.radio_button :nombre, "Esfera20"
                  = f.label "Esfera 20"
                  %br
                  = f.radio_button :nombre, "Esfera80"
                  = f.label "Esfera 80"
                  %br
                  = f.radio_button :nombre, "Esfera320"
                  = f.label "Esfera 320"
        %div.panel
          %div.panel-wrapper
            = f.label t(:color_fondo)
            %br
            = f.text_field :color_fondo, {:class => "selector_color"}
            %div{:id => "colorpicker_recortable_color_fondo"}
            = f.label t(:color_aristas)
            %br
            = f.text_field :color_aristas, {:class => "selector_color"}
            %div{:id => "colorpicker_recortable_color_aristas"}
            = f.radio_button :grosor_aristas, "Fino"
            = f.label "Fino"
            %br
            = f.radio_button :grosor_aristas, "Normal"
            = f.label "Normal"
            %br
            = f.radio_button :grosor_aristas, "Medio"
            = f.label "Medio"
            %br
            = f.radio_button :grosor_aristas, "Grueso"
            = f.label "Grueso"
            = f.label t(:textura)
            %br
            = f.file_field :textura, :size => "10"
            - if @recortable.textura
              = image_tag @recortable.textura.url(:thumb)
            %table
              %tr
                %td
                %td X
                %td Y
              %tr
                %td Tamaño
                %td= f.text_field :tamanyo_x
                %td= f.text_field :tamanyo_y
              %tr
                %td Desplazamiento
                %td= f.text_field :posicion_x
                %td= f.text_field :posicion_y
              %tr
                %td Repetir
                %td= f.check_box :repetir_x
                %td= f.check_box :repetir_y
            = f.submit t(:previsualizar)
        %div.panel
          %div.panel-wrapper
            = f.submit t(:generar)
            %p
            = link_to t(:cancelar), root_path
        .clear
    

app/views/recortables/_form.html_1.haml
%div{:id => "slider_imagenes"}

  %ul
  - lista_imagenes_recortable.each do |i|
    %li
      = image_tag i, :size => "400x400", :id => "imagen_cabecera"


%div{:id => "slider_formulario"}
  - semantic_form_for @recortable, :html => {:multipart => true} do |f|
    = f.error_messages
    %ul
      %li
        %div.pantalla_formulario
          %table
            %tr
              %td
                = f.label "Bolo 16"
                = f.radio_button :nombre, "Bolo16"
                %br
                = f.label "Bolo 35"
                = f.radio_button :nombre, "Bolo35"
                %br
                = f.label "Bolo 70"
                = f.radio_button :nombre, "Bolo70"
                %br
                = f.label "Bolo 154"
                = f.radio_button :nombre, "Bolo154"
                %br
                = f.label "Bolo 340"
                = f.radio_button :nombre, "Bolo340"                
              %td
                = f.label "Cono r=h"
                = f.radio_button :nombre, "Cono_r_h"
                %br
                = f.label "Cono r=2h"
                = f.radio_button :nombre, "Cono_r_2h"
                %br
                = f.label "Cono 2r=h"
                = f.radio_button :nombre, "Cono_2r_h"
                %br
                = f.label "Cono 4r=h"
                = f.radio_button :nombre, "Cono_4r_h"                
              %td
                = f.label "Esfera 20"
                = f.radio_button :nombre, "Esfera20"
                %br
                = f.label "Esfera 80"
                = f.radio_button :nombre, "Esfera80"
                %br
                = f.label "Esfera 320"
                = f.radio_button :nombre, "Esfera320"
      %li
        %div.pantalla_formulario
          %table
            %tr
              %td
                = f.label t(:color_fondo)
                %br
                = f.text_field :color_fondo, {:class => "selector_color"}
                %div{:id => "colorpicker_recortable_color_fondo", :class => "picker"}
                %br
                = f.label t(:textura)
                %br
                = f.file_field :textura
                - if @recortable.textura
                  %br
                  = image_tag @recortable.textura.url(:thumb)
              %td
                = f.label t(:color_aristas)
                %br
                = f.text_field :color_aristas, {:class => "selector_color"}
                %div{:id => "colorpicker_recortable_color_aristas", :class => "picker"}
                = f.label t(:grosor_aristas)
                %br
                = f.label "Fino"
                = f.radio_button :grosor_aristas, "Fino"
                %br
                = f.label "Medio"
                = f.radio_button :grosor_aristas, "Medio"
                %br
                = f.label "Grueso"
                = f.radio_button :grosor_aristas, "Grueso"
          %br

          = f.submit t(:previsualizar)
      %li
        %div.pantalla_formulario
          = f.submit t(:generar)
          %p
          = link_to t(:cancelar), root_path

    

app/views/recortables/_form.html_2.haml
#formulario
  %div{:id => "slider_formulario"}
    - semantic_form_for @recortable, :html => {:multipart => true, :class => "bp"} do |f|
      /= f.error_messages
      %ul
        %li
          %div.caja
            %table
              %tr
                %td
                  = f.radio_button :nombre, "Bolo16"
                  = f.label "Bolo 16"
                  %br
                  = f.radio_button :nombre, "Bolo35"
                  = f.label "Bolo 35"
                  %br
                  = f.radio_button :nombre, "Bolo70"
                  = f.label "Bolo 70"
                  %br
                  = f.radio_button :nombre, "Bolo154"
                  = f.label "Bolo 154"
                  %br
                  = f.radio_button :nombre, "Bolo340"
                  = f.label "Bolo 340"
                %td
                  = f.radio_button :nombre, "Cono_r_h"
                  = f.label "Cono r=h"
                  %br
                  = f.radio_button :nombre, "Cono_r_2h"
                  = f.label "Cono r=2h"
                  %br
                  = f.radio_button :nombre, "Cono_2r_h"
                  = f.label "Cono 2r=h"
                  %br
                  = f.radio_button :nombre, "Cono_4r_h"
                  = f.label "Cono 4r=h"
                %td
                  = f.radio_button :nombre, "Esfera20"
                  = f.label "Esfera 20"
                  %br
                  = f.radio_button :nombre, "Esfera80"
                  = f.label "Esfera 80"
                  %br
                  = f.radio_button :nombre, "Esfera320"
                  = f.label "Esfera 320"
        %li
          %div.caja
            %div.bloque.c_fondo
              = f.label t(:color_fondo)
              %br
              = f.text_field :color_fondo, {:class => "selector_color"}
              %div{:id => "colorpicker_recortable_color_fondo"}

            %div.bloque.c_aristas
              = f.label t(:color_aristas)
              %br
              = f.text_field :color_aristas, {:class => "selector_color"}
              %div{:id => "colorpicker_recortable_color_aristas"}

            %div.bloque.g_aristas
              = f.radio_button :grosor_aristas, "Fino"
              = f.label "Fino"
              %br
              = f.radio_button :grosor_aristas, "Normal"
              = f.label "Normal"
              %br
              = f.radio_button :grosor_aristas, "Medio"
              = f.label "Medio"
              %br
              = f.radio_button :grosor_aristas, "Grueso"
              = f.label "Grueso"

            %div.bloque.textura
              = f.label t(:textura)
              %br
              = f.file_field :textura, :size => "10"
              - if @recortable.textura
                = image_tag @recortable.textura.url(:thumb)
              %table
                %tr
                  %td
                  %td X
                  %td Y
                %tr
                  %td Tamaño
                  %td= f.text_field :tamanyo_x
                  %td= f.text_field :tamanyo_y
                %tr
                  %td Desplazamiento
                  %td= f.text_field :posicion_x
                  %td= f.text_field :posicion_y
                %tr
                  %td Repetir
                  %td= f.check_box :repetir_x
                  %td= f.check_box :repetir_y

            %div.bloque.previsualizar
              = f.submit t(:previsualizar)
        %li
          %div.caja
            = f.submit t(:generar)
            %p
            = link_to t(:cancelar), root_path
    .clear
    

app/views/recortables/_imagenes.html.haml
#imagenes
  %div{:class => "coda-slider-wrapper"}
    %div{:class=>"coda-slider preload", :id=>"coda-slider-imagenes"}
      - lista_imagenes_recortable.each do |i|
        %div.panel
          %div.panel-wrapper
            %div.centrada
              = image_tag i, :size => "400x400"

app/views/recortables/edit.html.haml
/- title "Edición del Recortable"

= render :partial => 'imagenes'
= render :partial => 'form'
.clear

app/views/recortables/index.html.erb
<% title "Recortables" %>

<table>
  <tr>
    <th>Numero Gajos</th>
    <th>Numero U</th>
    <th>Numero V</th>
    <th>Textura</th>
    <th>Ancho Textura X</th>
    <th>Ancho Textura Y</th>
    <th>Desplazamiento Textura X</th>
    <th>Desplazamiento Textura Y</th>
    <th>Rojo</th>
    <th>Verde</th>
    <th>Azul</th>
    <th>Repite Horizontal</th>
    <th>Repite Vertical</th>
    <th>Malla Rojo</th>
    <th>Malla Verde</th>
    <th>Malla Azul</th>
    <th>Malla Tamanyo</th>
    <th>Fin</th>
  </tr>
  <% for recortable in @recortables %>
    <tr>
      <td><%=h recortable.numero_gajos %></td>
      <td><%=h recortable.numero_u %></td>
      <td><%=h recortable.numero_v %></td>
      <td><%=h recortable.textura %></td>
      <td><%=h recortable.ancho_textura_x %></td>
      <td><%=h recortable.ancho_textura_y %></td>
      <td><%=h recortable.desplazamiento_textura_x %></td>
      <td><%=h recortable.desplazamiento_textura_y %></td>
      <td><%=h recortable.rojo %></td>
      <td><%=h recortable.verde %></td>
      <td><%=h recortable.azul %></td>
      <td><%=h recortable.repite_horizontal %></td>
      <td><%=h recortable.repite_vertical %></td>
      <td><%=h recortable.malla_rojo %></td>
      <td><%=h recortable.malla_verde %></td>
      <td><%=h recortable.malla_azul %></td>
      <td><%=h recortable.malla_tamanyo %></td>
      <td><%=h recortable.fin %></td>
      <td><%= link_to "Show", recortable %></td>
      <td><%= link_to "Edit", edit_recortable_path(recortable) %></td>
      <td><%= link_to "Destroy", recortable, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Recortable", new_recortable_path %></p>

app/views/recortables/index.html.haml
- title "Recortables"

%table
  %tr
    %th Modelo
    %th Complejidad
    %th Color de fondo
    %th Color de aristas
    %th Grosor de aristas
    %th Textura
  - for recortable in @recortables
    %tr
      %td=  recortable.modelo.nombre
      %td=  recortable.complejidad
      %td=  recortable.color_fondo
      %td=  recortable.color_aristas
      %td=  recortable.grosor_aristas
      %td=  recortable.textura
      %td= link_to "Show", recortable
      %td= link_to "Edit", edit_recortable_path(recortable)
      %td= link_to "Destroy", recortable, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Recortable", new_recortable_path

app/views/recortables/new.html.haml
- title t(:nuevo_recortable)
= render :partial => 'imagenes'
= render :partial => 'form'

.clear

app/views/recortables/show.html.erb
<% title "Recortable" %>

<p>
  <strong>Numero Gajos:</strong>
  <%=h @recortable.numero_gajos %>
</p>
<p>
  <strong>Numero U:</strong>
  <%=h @recortable.numero_u %>
</p>
<p>
  <strong>Numero V:</strong>
  <%=h @recortable.numero_v %>
</p>
<p>
  <strong>Textura:</strong>
  <%=h @recortable.textura %>
</p>
<p>
  <strong>Ancho Textura X:</strong>
  <%=h @recortable.ancho_textura_x %>
</p>
<p>
  <strong>Ancho Textura Y:</strong>
  <%=h @recortable.ancho_textura_y %>
</p>
<p>
  <strong>Desplazamiento Textura X:</strong>
  <%=h @recortable.desplazamiento_textura_x %>
</p>
<p>
  <strong>Desplazamiento Textura Y:</strong>
  <%=h @recortable.desplazamiento_textura_y %>
</p>
<p>
  <strong>Rojo:</strong>
  <%=h @recortable.rojo %>
</p>
<p>
  <strong>Verde:</strong>
  <%=h @recortable.verde %>
</p>
<p>
  <strong>Azul:</strong>
  <%=h @recortable.azul %>
</p>
<p>
  <strong>Repite Horizontal:</strong>
  <%=h @recortable.repite_horizontal %>
</p>
<p>
  <strong>Repite Vertical:</strong>
  <%=h @recortable.repite_vertical %>
</p>
<p>
  <strong>Malla Rojo:</strong>
  <%=h @recortable.malla_rojo %>
</p>
<p>
  <strong>Malla Verde:</strong>
  <%=h @recortable.malla_verde %>
</p>
<p>
  <strong>Malla Azul:</strong>
  <%=h @recortable.malla_azul %>
</p>
<p>
  <strong>Malla Tamanyo:</strong>
  <%=h @recortable.malla_tamanyo %>
</p>
<p>
  <strong>Fin:</strong>
  <%=h @recortable.fin %>
</p>

<p>
  <%= link_to "Edit", edit_recortable_path(@recortable) %> |
  <%= link_to "Destroy", @recortable, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", recortables_path %>
</p>

app/views/recortables/show.html.haml
- title "Recortable"

%p
  %strong Modelo:
  = @recortable.nombre

%p
  %strong Complejidad:
  =h @recortable.complejidad

%p
  %strong Color de fondo:
  =h @recortable.color_fondo

%p
  %strong Color aristas:
  =h @recortable.color_aristas

%p
  %strong Grosor aristas:
  =h @recortable.grosor_aristas

%p
  %strong Textura:
  =h @recortable.textura


%p
  = link_to "Edit", edit_recortable_path(@recortable) 
  = link_to "Destroy", @recortable, :confirm => 'Are you sure?', :method => :delete  
  = link_to "View All", recortables_path 