config/routes.rb
Recortables3d::Application.routes.draw do

  resources :imagenes
  resources :modelos
  resources :recortables

  resource :bienvenida, :only => :show, :controller => :bienvenida

   root :to => "bienvenida#show"

end

app/models/modelo.rb
class Modelo < ActiveRecord::Base

  has_many :recortables
  attr_accessible :nombre

  validates_presence_of :nombre
  validates_uniqueness_of :nombre

  def self.lista_select
    #TODO: Buscar la forma de traducir los modelos.
    all.map{|k| [k.nombre,k.id]}
  end


end

# == Schema Information
#
# Table name: modelos
#
#  id         :integer(4)      not null, primary key
#  nombre     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/modelos_controller.rb
class ModelosController < ApplicationController
  def index
    @modelos = Modelo.all
  end
  
  def show
    @modelo = Modelo.find(params[:id])
  end
  
  def new
    @modelo = Modelo.new
  end
  
  def create
    @modelo = Modelo.new(params[:modelo])
    if @modelo.save
      flash[:notice] = "Successfully created modelo."
      redirect_to @modelo
    else
      render :action => 'new'
    end
  end
  
  def edit
    @modelo = Modelo.find(params[:id])
  end
  
  def update
    @modelo = Modelo.find(params[:id])
    if @modelo.update_attributes(params[:modelo])
      flash[:notice] = "Successfully updated modelo."
      redirect_to @modelo
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @modelo = Modelo.find(params[:id])
    @modelo.destroy
    flash[:notice] = "Successfully destroyed modelo."
    redirect_to modelos_url
  end
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/views/modelos/_form.html.haml
- form_for @modelo do |f|
  = f.error_messages
  %p
    = f.label :nombre
    %br
    = f.text_field :nombre
  %p
    = f.submit "Submit"

app/views/modelos/edit.html.haml
- title "Edit Modelo"

= render :partial => 'form'

%p
  = link_to "Show", modelo_path(@modelo)
  |
  = link_to "View All", modelos_path

app/views/modelos/index.html.haml
- title "Modelos"

%table
  %tr
    %th Nombre
  - for modelo in @modelos
    %tr
      %td= h modelo.nombre
      %td= link_to 'Show', modelo
      %td= link_to 'Edit', edit_modelo_path(modelo)
      %td= link_to 'Destroy', modelo, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Modelo", new_modelo_path

app/views/modelos/new.html.haml
- title "New Modelo"

= render :partial => 'form'

%p= link_to "Back to List", modelos_path

app/views/modelos/show.html.haml
- title "Modelo"

%p
  %strong Nombre:
  =h @modelo.nombre

%p
  = link_to "Edit", edit_modelo_path(@modelo)
  |
  = link_to "Destroy", @modelo, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", modelos_path